"""LLM API Gateway Server - FastAPI application that centralizes LLM API access.

This gateway provides:
- Centralized API key management
- Structured logging and monitoring
- Unified interface for multiple LLM providers
"""

from typing import Any

from fastapi import FastAPI, HTTPException, status
from fastapi.responses import JSONResponse
from pydantic import BaseModel, create_model

from src.api_gateway.gateway_service import gateway_service
from src.api_gateway.models import (
    GatewayErrorResponse,
    GatewayHealthResponse,
    GatewayRequest,
    GatewayResponse,
)
from src.api_gateway.monitoring import gateway_monitor
from src.logger import make_logger

logger = make_logger(__name__)


def json_schema_to_pydantic(json_schema: dict[str, Any]) -> type[BaseModel]:
    """Convert a JSON schema to a Pydantic model.

    This function recreates a Pydantic model from a JSON schema generated by
    BaseModel.model_json_schema(). This is necessary because the gateway receives
    schemas as dictionaries but needs Pydantic models to pass to LLM APIs.

    Args:
        json_schema: JSON schema dictionary from model_json_schema()

    Returns:
        A dynamically created Pydantic model class

    Raises:
        ValueError: If schema is invalid or unsupported
    """
    if not json_schema:
        raise ValueError("Invalid JSON schema: schema is empty or None")

    # The schema might be wrapped or direct - handle both cases
    if "properties" not in json_schema:
        # Check if it's a reference or has nested structure
        if "$ref" in json_schema:
            raise ValueError("Top-level schema cannot be a reference")
        raise ValueError(f"Invalid JSON schema: missing 'properties' field. Keys found: {list(json_schema.keys())}")

    model_name = json_schema.get("title", "DynamicModel")
    properties = json_schema.get("properties", {})
    required_fields = set(json_schema.get("required", []))
    definitions = json_schema.get("$defs", {})

    # Build field definitions for create_model
    field_definitions = {}

    for field_name, field_schema in properties.items():
        try:
            field_type = _get_field_type(field_schema, definitions)
            is_required = field_name in required_fields

            if is_required:
                field_definitions[field_name] = (field_type, ...)
            else:
                default_value = field_schema.get("default", None)
                field_definitions[field_name] = (field_type, default_value)
        except Exception as e:
            logger.error(f"Error processing field '{field_name}': {e}")
            raise ValueError(f"Failed to process field '{field_name}': {str(e)}")

    # Create the dynamic model
    return create_model(model_name, **field_definitions)


def _get_field_type(field_schema: dict[str, Any], definitions: dict[str, Any]) -> Any:
    """Get Python type from JSON schema field definition.

    Args:
        field_schema: Field schema definition
        definitions: Schema definitions for nested models

    Returns:
        Python type annotation
    """
    # Handle references to definitions
    if "$ref" in field_schema:
        ref_path = field_schema["$ref"].split("/")[-1]
        if ref_path in definitions:
            ref_schema = definitions[ref_path]
            # Check if it's an enum
            if "enum" in ref_schema:
                # For enums, we just use str as the base type
                return str
            # Otherwise, it's a nested model
            return json_schema_to_pydantic(ref_schema)
        raise ValueError(f"Definition not found: {ref_path}")

    # Handle arrays
    if field_schema.get("type") == "array":
        items_schema = field_schema.get("items", {})
        item_type = _get_field_type(items_schema, definitions)
        return list[item_type]

    # Handle enums
    if "enum" in field_schema:
        return str

    # Handle basic types
    type_mapping = {
        "string": str,
        "integer": int,
        "number": float,
        "boolean": bool,
        "object": dict,
    }

    field_type = field_schema.get("type", "string")
    return type_mapping.get(field_type, str)


# Create FastAPI application
app = FastAPI(
    title="LLM API Gateway",
    description="Centralized gateway for managing and routing LLM API requests",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)


@app.exception_handler(Exception)
async def global_exception_handler(request, exc):
    """Global exception handler for unhandled errors."""
    logger.error(f"Unhandled exception: {type(exc).__name__}: {str(exc)}")
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content=GatewayErrorResponse(
            error=str(exc),
            error_type=type(exc).__name__,
        ).model_dump(),
    )


@app.get("/health", response_model=GatewayHealthResponse, tags=["Health"])
async def health_check():
    """Health check endpoint for the gateway.

    Returns the health status of the gateway and availability of LLM providers.
    """
    # In production, you would check actual provider availability
    providers_available = {
        "openai": True,
        "gemini": True,
    }

    return GatewayHealthResponse(providers_available=providers_available)


@app.post("/v1/generate", response_model=GatewayResponse, tags=["Gateway"])
async def generate(request: GatewayRequest):
    """Generate content using LLM through the gateway.

    This endpoint centralizes all LLM API calls, providing:
    - Secure API key management (keys never exposed to clients)
    - Request/response logging and monitoring
    - Consistent error handling

    Args:
        request: Gateway request with LLM parameters

    Returns:
        Gateway response with generated content and metadata

    Raises:
        HTTPException: If request fails or provider is not supported
    """
    # Generate unique request ID
    request_id = gateway_monitor.generate_request_id()

    try:
        # Convert JSON schema to Pydantic model
        response_format_model = None
        if request.response_format:
            try:
                logger.debug(f"Received response_format schema: {request.response_format}")
                response_format_model = json_schema_to_pydantic(request.response_format)
                logger.info(f"Successfully converted JSON schema to Pydantic model: {response_format_model.__name__}")
            except Exception as e:
                logger.error(f"Failed to convert JSON schema to Pydantic model: {e}")
                logger.error(
                    f"Schema keys: {list(request.response_format.keys()) if isinstance(request.response_format, dict) else 'not a dict'}"
                )
                raise ValueError(f"Invalid response_format schema: {str(e)}")

        # Process the request through the gateway
        content, processing_time_ms = await gateway_service.process_request(
            request_id=request_id,
            provider=request.provider,
            model=request.model,
            prompt=request.prompt,
            response_format=response_format_model,
            client_id=request.client_id,
        )

        return GatewayResponse(
            content=content,
            provider=request.provider,
            model=request.model,
            processing_time_ms=processing_time_ms,
            request_id=request_id,
        )

    except ValueError as e:
        # Invalid provider or configuration
        gateway_monitor.log_error(
            request_id,
            "ValidationError",
            str(e),
            request.provider,
            request.model,
        )
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=GatewayErrorResponse(
                error=str(e),
                error_type="ValidationError",
                request_id=request_id,
            ).model_dump(),
        )

    except Exception as e:
        # Other errors (network issues, API errors, etc.)
        gateway_monitor.log_error(
            request_id,
            type(e).__name__,
            str(e),
            request.provider,
            request.model,
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=GatewayErrorResponse(
                error=str(e),
                error_type=type(e).__name__,
                request_id=request_id,
            ).model_dump(),
        )


if __name__ == "__main__":
    import uvicorn

    logger.info("Starting LLM API Gateway Server...")
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8080,
        log_level="info",
    )
