from src.prompt.multi_agent_prompt import (
    AMENDMENT_PROPOSER_SYSTEM_PROMPT,
    CLAUSE_CLASSIFIER_SYSTEM_PROMPT,
    DIFF_CHECKER_SYSTEM_PROMPT,
    DOCUMENT_PARSER_SYSTEM_PROMPT,
    ORCHESTRATOR_SYSTEM_PROMPT,
    REPORT_GENERATOR_SYSTEM_PROMPT,
    RISK_ASSESSMENT_SYSTEM_PROMPT,
    SYNTHESIZER_SYSTEM_PROMPT,
    make_amendment_proposer_prompt,
    make_clause_classifier_prompt,
    make_diff_checker_prompt,
    make_document_parser_prompt,
    make_orchestrator_prompt,
    make_report_generator_prompt,
    make_risk_assessment_prompt,
    make_synthesizer_prompt,
)

__all__ = [
    "AMENDMENT_PROPOSER_SYSTEM_PROMPT",
    "CLAUSE_CLASSIFIER_SYSTEM_PROMPT",
    "DIFF_CHECKER_SYSTEM_PROMPT",
    "DOCUMENT_PARSER_SYSTEM_PROMPT",
    "ORCHESTRATOR_SYSTEM_PROMPT",
    "REPORT_GENERATOR_SYSTEM_PROMPT",
    "RISK_ASSESSMENT_SYSTEM_PROMPT",
    "SYNTHESIZER_SYSTEM_PROMPT",
    "make_amendment_proposer_prompt",
    "make_clause_classifier_prompt",
    "make_diff_checker_prompt",
    "make_document_parser_prompt",
    "make_orchestrator_prompt",
    "make_report_generator_prompt",
    "make_risk_assessment_prompt",
    "make_synthesizer_prompt",
]
