"""LLM API Gateway Server - FastAPI application that centralizes LLM API access.

This gateway provides:
- Centralized API key management
- Structured logging and monitoring
- Unified interface for multiple LLM providers
"""

from typing import Any

from fastapi import FastAPI, HTTPException, status
from fastapi.responses import JSONResponse
from pydantic import BaseModel, create_model

from src.api_gateway.gateway_service import gateway_service
from src.api_gateway.models import (
    GatewayErrorResponse,
    GatewayHealthResponse,
    GatewayRequest,
    GatewayResponse,
)
from src.api_gateway.monitoring import gateway_monitor
from src.logger import make_logger

logger = make_logger(__name__)


def json_schema_to_pydantic(json_schema: dict[str, Any]) -> type[BaseModel]:
    """Convert a JSON schema to a Pydantic model.

    Recreates a Pydantic model from a JSON schema generated by model_json_schema().
    The gateway receives schemas as dictionaries but needs Pydantic models to pass to LLM APIs.
    """
    if not json_schema:
        raise ValueError("Invalid JSON schema: schema is empty or None")

    if "properties" not in json_schema:
        if "$ref" in json_schema:
            raise ValueError("Top-level schema cannot be a reference")
        raise ValueError(f"Invalid JSON schema: missing 'properties' field. Keys found: {list(json_schema.keys())}")

    model_name = json_schema.get("title", "DynamicModel")
    properties = json_schema.get("properties", {})
    required_fields = set(json_schema.get("required", []))
    definitions = json_schema.get("$defs", {})
    field_definitions = {}

    for field_name, field_schema in properties.items():
        try:
            field_type = _get_field_type(field_schema, definitions)
            is_required = field_name in required_fields

            if is_required:
                field_definitions[field_name] = (field_type, ...)
            else:
                default_value = field_schema.get("default", None)
                field_definitions[field_name] = (field_type, default_value)
        except Exception as e:
            logger.error(f"Error processing field '{field_name}': {e}")
            raise ValueError(f"Failed to process field '{field_name}': {str(e)}")

    return create_model(model_name, **field_definitions)


def _get_field_type(field_schema: dict[str, Any], definitions: dict[str, Any]) -> Any:
    """Get Python type from JSON schema field definition."""
    if "$ref" in field_schema:
        ref_path = field_schema["$ref"].split("/")[-1]
        if ref_path in definitions:
            ref_schema = definitions[ref_path]
            if "enum" in ref_schema:
                return str
            return json_schema_to_pydantic(ref_schema)
        raise ValueError(f"Definition not found: {ref_path}")

    if field_schema.get("type") == "array":
        items_schema = field_schema.get("items", {})
        item_type = _get_field_type(items_schema, definitions)
        return list[item_type]

    if "enum" in field_schema:
        return str

    type_mapping = {
        "string": str,
        "integer": int,
        "number": float,
        "boolean": bool,
        "object": dict,
    }

    field_type = field_schema.get("type", "string")
    return type_mapping.get(field_type, str)


app = FastAPI(
    title="LLM API Gateway",
    description="Centralized gateway for managing and routing LLM API requests",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)


@app.exception_handler(Exception)
async def global_exception_handler(request, exc):
    """Global exception handler for unhandled errors."""
    logger.error(f"Unhandled exception: {type(exc).__name__}: {str(exc)}")
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content=GatewayErrorResponse(
            error=str(exc),
            error_type=type(exc).__name__,
        ).model_dump(),
    )


@app.get("/health", response_model=GatewayHealthResponse, tags=["Health"])
async def health_check():
    """Health check endpoint returning gateway status and provider availability."""
    providers_available = {
        "openai": True,
        "gemini": True,
    }

    return GatewayHealthResponse(providers_available=providers_available)


@app.post("/v1/generate", response_model=GatewayResponse, tags=["Gateway"])
async def generate(request: GatewayRequest):
    """Generate content using LLM through the gateway.

    Centralizes all LLM API calls with secure key management, logging, and error handling.
    """
    request_id = gateway_monitor.generate_request_id()

    try:
        response_format_model = None
        if request.response_format:
            try:
                logger.debug(f"Received response_format schema: {request.response_format}")
                response_format_model = json_schema_to_pydantic(request.response_format)
                logger.info(f"Successfully converted JSON schema to Pydantic model: {response_format_model.__name__}")
            except Exception as e:
                logger.error(f"Failed to convert JSON schema to Pydantic model: {e}")
                logger.error(
                    f"Schema keys: {list(request.response_format.keys()) if isinstance(request.response_format, dict) else 'not a dict'}"
                )
                raise ValueError(f"Invalid response_format schema: {str(e)}")

        content, processing_time_ms = await gateway_service.process_request(
            request_id=request_id,
            provider=request.provider,
            model=request.model,
            prompt=request.prompt,
            response_format=response_format_model,
            client_id=request.client_id,
        )

        return GatewayResponse(
            content=content,
            provider=request.provider,
            model=request.model,
            processing_time_ms=processing_time_ms,
            request_id=request_id,
        )

    except ValueError as e:
        _handle_gateway_error(request_id, request, e, status.HTTP_400_BAD_REQUEST, "ValidationError")

    except Exception as e:
        _handle_gateway_error(request_id, request, e, status.HTTP_500_INTERNAL_SERVER_ERROR)


def _handle_gateway_error(
    request_id: str,
    request: GatewayRequest,
    error: Exception,
    status_code: int,
    error_type: str | None = None,
) -> None:
    """Handle gateway errors by logging and raising HTTPException."""
    resolved_error_type = error_type or type(error).__name__
    gateway_monitor.log_error(
        request_id,
        resolved_error_type,
        str(error),
        request.provider,
        request.model,
    )
    raise HTTPException(
        status_code=status_code,
        detail=GatewayErrorResponse(
            error=str(error),
            error_type=resolved_error_type,
            request_id=request_id,
        ).model_dump(),
    )


if __name__ == "__main__":
    import uvicorn

    logger.info("Starting LLM API Gateway Server...")
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8080,
        log_level="info",
    )
