[project]
name = "section-7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "anthropic>=0.58.2",
    "click>=8.2.1",
    "google-genai>=1.26.0",
    "openai>=1.97.0",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.2",
]
