"""AI Agent Framework with Forget, Replay, Speculate pattern.

This package is organized into two layers:

Core Layer (src.agent.core):
    Contains stable abstractions and base classes that rarely change.

Extension Layer (src.agent.extensions):
    Contains concrete implementations including:
    - Replay mechanism (WAL-based prompt replay after rollback)
    - Speculative execution (parallel-world branching)
    - Article generation pipeline with all three stages integrated
"""

from src.agent.core import (
    ActingState,
    Action,
    ActionType,
    AgentContext,
    AgentEvent,
    AgentState,
    AgentStatus,
    BaseAgent,
    CompletedState,
    ContextData,
    Edge,
    EdgeType,
    ErrorState,
    ExecutionController,
    ExecutionHandler,
    ExecutionLogEntry,
    ExecutionRequest,
    ExecutionResponse,
    GraphExecutionResult,
    GraphMediator,
    IdleState,
    Memory,
    MemorySnapshot,
    Message,
    MetadataDict,
    Node,
    NodeResult,
    NodeType,
    ParamValue,
    PausedState,
    StateTransition,
    StepInfo,
    Strategy,
    ThinkingState,
    Tool,
    ToolBox,
    ToolData,
    ToolParams,
    ToolResult,
    WaitingState,
)
from src.agent.extensions import (
    AgentBuilder,
    AgentNode,
    AggregatorNode,
    BaseStrategy,
    BranchDetector,
    CalculatorTool,
    CategorizableToolBox,
    ChainOfThoughtStrategy,
    ConfigurableAgent,
    ContextMemory,
    ConversationalMemory,
    CostLimitHandler,
    DangerousActionHandler,
    DecisionNode,
    LoopDetectionHandler,
    MaxStepsHandler,
    MemoryCaretaker,
    MultiStrategyAgent,
    ParallelGraphMediator,
    PromptLog,
    PromptLogEntry,
    PromptType,
    ReActStrategy,
    ReplayDecision,
    ReplayDiff,
    ReplayEngine,
    ReplayFilter,
    ReplayResult,
    SimpleGraphMediator,
    ToolRateLimitHandler,
    TreeOfThoughtStrategy,
    WebSearchTool,
    World,
    WorldManager,
    WorldStatus,
    WorldSummary,
    create_agent_from_config,
    create_default_controller,
)

__all__ = [
    "Action",
    "ActionType",
    "ActingState",
    "AgentBuilder",
    "AgentContext",
    "AgentEvent",
    "AgentNode",
    "AgentState",
    "AgentStatus",
    "AggregatorNode",
    "BaseAgent",
    "BaseStrategy",
    "BranchDetector",
    "CalculatorTool",
    "CategorizableToolBox",
    "ChainOfThoughtStrategy",
    "CompletedState",
    "ConfigurableAgent",
    "ContextData",
    "ContextMemory",
    "ConversationalMemory",
    "CostLimitHandler",
    "DangerousActionHandler",
    "DecisionNode",
    "Edge",
    "EdgeType",
    "ErrorState",
    "ExecutionController",
    "ExecutionHandler",
    "ExecutionLogEntry",
    "ExecutionRequest",
    "ExecutionResponse",
    "GraphExecutionResult",
    "GraphMediator",
    "IdleState",
    "LoopDetectionHandler",
    "MaxStepsHandler",
    "Memory",
    "MemoryCaretaker",
    "MemorySnapshot",
    "Message",
    "MetadataDict",
    "MultiStrategyAgent",
    "Node",
    "NodeResult",
    "NodeType",
    "ParallelGraphMediator",
    "ParamValue",
    "PausedState",
    "PromptLog",
    "PromptLogEntry",
    "PromptType",
    "ReActStrategy",
    "ReplayDecision",
    "ReplayDiff",
    "ReplayEngine",
    "ReplayFilter",
    "ReplayResult",
    "SimpleGraphMediator",
    "StateTransition",
    "StepInfo",
    "Strategy",
    "ThinkingState",
    "Tool",
    "ToolBox",
    "ToolData",
    "ToolParams",
    "ToolRateLimitHandler",
    "ToolResult",
    "TreeOfThoughtStrategy",
    "WaitingState",
    "WebSearchTool",
    "World",
    "WorldManager",
    "WorldStatus",
    "WorldSummary",
    "create_agent_from_config",
    "create_default_controller",
]
